#!/usr/bin/env bash

# shell prompt
PS1="\u@\h:\w $ "

# colors
CLICOLOR=1
LSCOLORS=ExFxBxDxCxegedabagacad

# aliases
alias pingg="ping google.com"
alias clean="rm -f *~ *.o *#"
alias ls="ls -GFh --color=auto"
alias tmux="tmux -2"  # launches tmux with support for 256 color terms
